version: '3.2'
services:
  redis:
    image: redis
    container_name: test_redis-cache
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/test_data
    entrypoint:
      redis-server --appendonly yes
    restart: always

  postgres:
    image: postgres:latest
    container_name: "test_typeorm-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "DominicPhan"
      POSTGRES_PASSWORD: "poopoo"
      POSTGRES_DB: "test_homies_blog"
    restart: always
  
  backend:
    container_name: test_hblog_backend
    build:
      context: .
      dockerfile: ./server/dockerfileTest
    ports:
      - '3001:3001'
    volumes:
      - './server:/usr/src/app'
      - './usr/src/app/node_modules'
    depends_on:
      - postgres
    links:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://test_redis-cache
      - PG_NAME=test_homies_blog